### ISSUE TITLE
custom css for selected file, folder

### ISSUE THREAD

**Issue by arunkumar413** [shunjizhan/React-Folder-Tree#62] opened 2022-06-15 15:37 UTC
I'd like to highlight the file name being edited currently.

I tried the below css but it didn't work. Could you please guide me on how to add my own css styles.

```
.TreeNodde .TreeNodeToolBar {
  background-color: gray;
}

.TreeNodde .editingName {
  background-color: blue;
}

```

**Comment by purbe** [comment] 2022-06-16 06:49
try this one 

.FolderTree .TreeNode .TreeNodeToolBar {
background-color: gray;
}

**Comment by shunjizhan** [comment] 2022-06-19 07:01
duplicate of #49,

**Closed as completed by shunjizhan** 2022-06-19 07:01 UTC
